### ISSUE TITLE
Add "video: career changers" to Q4 2019 project goal

### ISSUE THREAD

**Issue by Nirvikalpa108** [codemortals/documentation#1]
Hi @eddiejaoude!

Would it be possible for us to do our second instalment of the career changers YouTube livestream before the end of the year please? 

We said we would do this when we did the last one and I've spoken to some of the ladies and I know they're super excited about it!

I'm not sure if this is the right place to add this, but I saw a list of Q4 goals here and wondered if it could be added there? https://github.com/codemortals/documentation/projects/1#column-6204833

Thank you!
Amina ❤️

**Comment by eddiejaoude** [comment]
@Nirvikalpa108 thank you for raising the issue and reminding us ❤️  . Yes we can do it for sure this year! 🤓 

Awesome you have spoken to some ladies and they are keen 🎉 

Let's get a date in the diary from now. It will probably have to be October or November.

**Comment by Nirvikalpa108** [comment]
Yes! Shall we pencil in Monday 25 November 6pm?

**Comment by eddiejaoude** [comment]
Sounds good to us 🎉 , we look forward to it! We can confirm topics closer to the time.

I have added it to our road map https://github.com/codemortals/documentation/projects/1#card-25390998
